/******************************************************************************/
/*            Generated by IBExpert 2012.02.21 30/08/2013 00:48:21            */
/******************************************************************************/

SET SQL DIALECT 3;

SET NAMES NONE;

SET CLIENTLIB 'C:\Program Files (x86)\Firebird\Firebird_2_5\bin\fbclient.dll';

CREATE DATABASE 'E:\delphi\componentes\scutum\connection\databases\SCUTUM.fdb'
USER 'SYSDBA' PASSWORD 'masterkey'
PAGE_SIZE 16384
DEFAULT CHARACTER SET NONE COLLATION NONE;



/******************************************************************************/
/*                                 Generators                                 */
/******************************************************************************/

CREATE GENERATOR GEN_TBL_CLASSES_DB_ID;
SET GENERATOR GEN_TBL_CLASSES_DB_ID TO 3;



/******************************************************************************/
/*                                   Tables                                   */
/******************************************************************************/



CREATE TABLE TBL_CLASSES_DB (
    CDB_ID         INTEGER NOT NULL,
    CDB_NOME       VARCHAR(50) NOT NULL,
    CDB_BANCO      VARCHAR(50) NOT NULL,
    CDB_FRAMEWORK  VARCHAR(50) NOT NULL,
    CDB_UNIT       VARCHAR(50) NOT NULL
);

INSERT INTO TBL_CLASSES_DB (CDB_ID, CDB_NOME, CDB_BANCO, CDB_FRAMEWORK, CDB_UNIT) VALUES (1, 'TSCUTUMDatabaseFactoryFirebirdDbx', 'Firebird', 'DBX', 'SCUTUM.Connection.Firebird.DBX');
INSERT INTO TBL_CLASSES_DB (CDB_ID, CDB_NOME, CDB_BANCO, CDB_FRAMEWORK, CDB_UNIT) VALUES (2, 'TSCUTUMDatabaseFactoryFirebirdFireDac', 'Firebird', 'FireDac', 'SCUTUM.Connection.Firebird.FireDac');
INSERT INTO TBL_CLASSES_DB (CDB_ID, CDB_NOME, CDB_BANCO, CDB_FRAMEWORK, CDB_UNIT) VALUES (3, 'TSCUTUMDatabaseFactoryMSSQLFireDac', 'SQLServer', 'FireDac', 'SCUTUM.Connection.MSSQL.FireDac');

COMMIT WORK;



/******************************************************************************/
/*                                Primary Keys                                */
/******************************************************************************/

ALTER TABLE TBL_CLASSES_DB ADD CONSTRAINT PK_TBL_CLASSES_DB PRIMARY KEY (CDB_ID);


/******************************************************************************/
/*                                  Triggers                                  */
/******************************************************************************/


SET TERM ^ ;



/******************************************************************************/
/*                            Triggers for tables                             */
/******************************************************************************/



/* Trigger: TBL_CLASSES_DB_BI */
CREATE TRIGGER TBL_CLASSES_DB_BI FOR TBL_CLASSES_DB
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.cdb_id is null) then
    new.cdb_id = gen_id(gen_tbl_classes_db_id,1);
end
^

SET TERM ; ^

